# Generated by Django 4.1.2 on 2022-10-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('message', models.TextField()),
                ('author', models.CharField(blank='', max_length=100)),
                ('blog_img', models.ImageField(upload_to='')),
                ('Feild_area', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
